import type { Metadata } from "next";
import type { ReactNode } from "react";
import { Inter } from "next/font/google";
import { cn } from "@/lib/utils";
import "./globals.css";
import { sessionCached } from "@/auth";

const inter = Inter({
    subsets: ["latin"],
    weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: ReactNode;
}>) {
    sessionCached();
    return (
        <html lang="en">
            <body className={cn("min-h-screen bg-background font-sans antialiased", inter.className)}>{children}</body>
        </html>
    );
}
